-- =========================================================================
-- Orders bulk import support.
--
-- The Order Import wizard (reusing the generalized inventory-import engine)
-- needs to accept a few fields the Orders table has no column for yet:
-- Priority, Sales Person, Delivery Date, and Advance Paid. Balance Due is
-- deliberately NOT added as a writable column - it's derived from
-- total - advance_paid, generated by Postgres the same way Loose Diamonds'
-- selling_price is (see migration 0021), so it can never drift from that
-- rule via the app, an import, or a stray manual update.
--
-- All new columns are nullable/defaulted and purely additive - existing
-- rows and every current Orders code path (manual create/edit form, list,
-- detail page) are completely unaffected.
-- =========================================================================

create type public.order_priority as enum ('low', 'normal', 'high', 'urgent');

alter table public.orders
  add column priority public.order_priority not null default 'normal',
  add column sales_person text,
  add column delivery_date date,
  add column advance_paid numeric(12, 2) not null default 0,
  add column balance_due numeric(12, 2) generated always as (total - advance_paid) stored;

create index orders_priority_idx on public.orders (priority);
